services:
  transmission-pia:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-pia
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - ${DOWNLOADS_DIR}:/data
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=de_frankfurt
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_WEB_UI=flood-for-transmission
      # - TRANSMISSION_WEB_UI=transmissionic
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_USER}
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_PASSWORD}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=UTC
    ports:
      - "9092:9091"
      - "51413:51413"
      - "51413:51413/udp"

    networks:
      - transmission-net
    restart: unless-stopped

  transmission-rss:
    image: haugene/transmission-rss:latest
    container_name: transmission-rss
    volumes:
      - ./config/transmission-rss/transmission-rss.conf:/etc/transmission-rss.conf:ro
      - ./config/transmission-rss/seen.txt:/root/.config/transmission/seen
    environment:
      - DEBUG=true
    networks:
      - transmission-net
    depends_on:
      - transmission-pia
    restart: unless-stopped

networks:
  transmission-net:
    driver: bridge
